name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Download dependencies
      run: go mod download
      
    - name: Run all tests (includes unit and integration tests)
      run: go test -v ./...
      
    - name: Run integration tests specifically (with all dependencies)
      run: go test -v *.go -run="TestIntegration"
      
    - name: Run benchmarks
      run: go test -v *.go -bench=. -benchmem -run="Benchmark"
      
    - name: Check test coverage
      run: go test -v -coverprofile=coverage.out ./...
      
    - name: Upload coverage to Codecov (optional)
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
